# Generated by Django 2.2.1 on 2019-05-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
