# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0004_auto_20190528_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Planner/profile_pics/default.jpg', upload_to='Planner/profile_pics'),
        ),
    ]
