# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0007_auto_20190528_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='apps/Planner/static/images/'),
        ),
    ]
